docs/building_your_app.md

since the filename is `building_your_app`, I believe this should be corrected.

Update heading to Building Your App

---

docs/building_your_app.md
template/config.js
template/package.json

Electron Packager [8.0.0](https://github.com/electron-userland/electron-packager/releases/tag/v8.0.0) was released today. This PR upgrades `electron-packager` and removes the need to manually set the app version (as of [7.7.0](https://github.com/electron-userland/electron-packager/releases/tag/v7.7.0), it is inferred from the app's `package.json` if it is not specified).

Update for Electron Packager 8.0.0

---

template/tasks/release.js

The rest of tasks/release.js is formatted according to js-standard, and this prevents the only two linting errors in the project that appear when using js-standard style.

Tweak whitespace in tasks/release.js to comply with js-standard

---

template/.gitignore

I'm used to seeing coverage directories gitignored. Would this be something ***you*** want projects to gitignore by default?

Ignore unit-test-generated coverage directory

---

template/.gitignore

Don't track the webpack-compiled-distributed CSS.

Update template .gitignore to ignore compiled CSS

---

template/app/src/components/LandingPageView/Links.vue

Closes #77
`node-sass` was removed for Windows build compatibility. This removes use of leftover SCSS in the `Links.vue` component.

Remove leftover SCSS usage in template Links.vue

---

template/package.json

`babel-register` shows up twice when you choose `e2e`, which is incorrect.

fix duplicate babel-register

---

template/tasks/runner.js

When the compilation is succesfull but with warnings, the webpack message is:
`webpack: Compiled with warnings.`
When the compilation is succesfull, the webpack message is:
`webpack: Compiled  successfull.`

#14 update task runner to start electron after compilation with warnings

---

template/package.json
template/test/unit/karma.conf.js

The BABEL_ENV which was getting set for testing was getting overwritten by the BABEL_ENV set in webpack.renderer.config.js. Fixed it by declaring the BABEL_ENV in the karma config, similar to how it is done for e2e testing.
This should fix #181 and istanbul should generate correct coverage reports now.

Fixed karma-coverage reporting no data

---

template/webpack.main.config.js
template/webpack.renderer.config.js

The settings is the main config file never used.
And in the renderer config there that comma is indeed dangling.

Fix eslint errors in generated webpack files

---

template/.electron-vue/dev-runner.js
template/.electron-vue/webpack.renderer.config.js
template/package.json

Add a stderr handler in dev-runner script in order to capture the outputs of console.warn and console.error as well.
In addition, update some dependencies and fix a typo in webpack.renderer.config.js.

Add a stderr handler in dev-runner.js.

---

meta.js
template/.travis.yml
template/appveyor.yml
template/package.json

update electron-builder to 19.x
make electron-builder as default choice because electron-builder handles all aspects of building Electron app (and in any case by alphabet)
1. electron-builder and electron-osx-sign fully support macOS Sierra.
2. electron-builder 19.6.0 bundles wine and all other tools to build electron app for Windows on macOS without setup, but macOS Sierra is required.
3. macOS Sierra is required to sign DMG.
4. Windows Server 2016 should be used to build appx. Yes — electron-builder bundles all required tools, but in any case it is better to use Windows Server 2016.
5. The same OS version locally and on CI.
electron-rebuild dependency is removed if electron-builder used — useless dependency.
JFYI: electron-builder app, Electrify, will use this boilerplate …

update travis/appveyor to use latest OS version

---

template/.electron-vue/dev-runner.js

The `setup` option is deprecated and will be removed in v3. Please update your config to use `before`

fix the `setup` option is deprecated.

---

README.md

Added Pomotroid app, built with electron-vue, to the _Made with electron-vue_ section in the README. Thanks for the framework! It's a real pleasure to work with.

Added Pomotroid app to the README

---

template/appveyor.yml

Remove "choco install yarn --ignore-dependencies" from appveyor.yml
Since Yarn 1.5.1 is already installed on AppVeyor, there is no need to install it again.
It produce a error code 1603 with this line, build success without this line.
source? : [https://www.appveyor.com/docs/build-environment/#pre-installed-software](https://www.appveyor.com/docs/build-environment/#pre-installed-software)

Update appveyor.yml, remove "choco install yarn ..."

---

template/.electron-vue/dev-runner.js

In development mode, it fetches electrons version instead of app's version which is in pacakage.json. (as #375 )
```js
// src/main/index.js
import { app } from 'electron'
console.log('getVersion', app.getVersion()) // getVersion 1.7.12
```
And, I find a solution from [electron/electron#7085](https://github.com/electron/electron/issues/7085)
> In development the version returned by app.getVersion() depends on how you launched your app.
I got the right Version of App when I change the path from `path.join(__dirname, '../dist/electron/main.js')` to `'.'`
This issue confuse me alot when I using `electron-updater`.
-------
* Electron version: 1.7.12
* Node version: 7.9.0
* NPM version: 5.6.0
* Platform: win32
* Vue-cli version: 2.9.3

Fix app.getVersion() getting electron lib version #375

---

template/.eslintrc.js
template/package.json

some chai tests may trigger the eslint no-used-expressions
```
✘  http://eslint.org/docs/rules/no-unused-expressions  Expected an assignment or function call and instead saw an expression
path/to/test.spec.js:62:9
expect(await proxy[ID_APPARECCHIO]).to.not.be.undefined
^
✘ 1 problem (1 error, 0 warnings)
Errors:
1  http://eslint.org/docs/rules/no-unused-expressions
```
the solution is a copy & paste from [Eslint docs](https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files)

add rule no-unused-expressions=off

---

README.md

IntelTracker is a project intended for players and speed-runners of No One Lives Forever (2000, PC). It tracks what intelligence items are found in the game as the player finds them. It uses ``electron-vue`` to allow it to run locally as an application, with ``vue`` handling UI updates and customization, and save-file watching using ``chokidar``.
Thanks for the great ``electron-vue`` tool; it made initial setup trivially easy!

Added IntelTracker to "made with" section

---

template/.travis.yml

Was encountering error in Travis-CI:
```
0.75s$ mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
/Users/travis/.travis/functions: line 109:  2911 Segmentation fault: 11  /tmp/git-lfs/git-lfs pull
The command "mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull" failed and exited with 139 during .
```
Travis-CI now supports git-lfs in Linux by default and recommends …

fix Travis-CI error using git lfs

---

template/src/main/index.js

When using `vuex-electron`, this line of import code helps the `mapActions` function work properly.

Fix a bug when using vuex-electron

---

template/.electron-vue/webpack.renderer.config.js

Remove hot-module-replacement related code from the bundled file in the production mode

fix: remove hot-module-replacement in production mode

---

template/.electron-vue/build.js
template/package.json

refs #924 
`multispinner` is not maintained, and it has security issues. So I propose replacing `multispinner` with another one.
In this pull request, I am using `listr`. `listr` can execute multiple tasks in parallel, so I think that it is enough to meet this requirement.
I have already used this script in my project, it looks like here:

Replace multispinner with listr in build.js

---

template/.travis.yml

due to Travis CI has a [guide](https://docs.travis-ci.com/user/customizing-the-build/#Git-LFS) to handle Git LFS, we should change this or it may cause problem under osx sometimes. ([like this](https://travis-ci.org/LightouchDev/MasterVyrn/jobs/302319564))
Git LFS is installed on Trusty by default.

Install git-lfs nicely
