tasks/runner.js

➜  electron-vue git:(master) ✗ npm run dev
> electron-vue@0.1.0 dev /Users/wuweixing/lab/sqlwwx/electron/electron-vue
> node tasks/runner.js
Starting webpack-dev-server...
/Users/wuweixing/lab/sqlwwx/electron/electron-vue/tasks/runner.js:18
data.trim().replace(/\n/g, '\n' + repeat(' ', command.length + 2)) +
^
TypeError: data.trim is not a function
at format (/Users/wuweixing/lab/sqlwwx/electron/electron-vue/tasks/runner.js:18:10)
at Socket.child.stdout.on.data (/Users/wuweixing/lab/sqlwwx/electron/electron-vue/tasks/runner.js:32:17)
at emitOne (events.js:101:20)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:172:18)
at Socket.Readable.push (_stream_readable.js:130:10)
at Pipe.onread (net.js:542:20)
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" …

data is buffer on node 6

---

.eslintrc.js

https://github.com/vuejs-templates/webpack/issues/116

Fix errors in node 6 on Windows x64

---

template/app/src/vuex/store.js

actions & getters are exported individually.

Fix import actions & getters for vue@next

---

template/package.json
template/test/unit/karma.conf.js

Same fix as #186, but for the new #dev project structure.

Fixed karma-coverage reporting no data (for #dev project structure)

---

template/.electron-vue/dev-runner.js

I forgot where i found the solution.

prevent ERR_INCOMPLETE_CHUNKED_ENCODING

---

template/src/renderer/store/modules/Counter.js

Fixed incorrect increment/decrement logic

Update Counter.js - fixed typos

---

README.md

My small app added to README. It may be usable for somebody as an example, because it's very simple :) Regards

'Backlog' app added to list 'made with electron-vue'

---

template/package.json
template/src/renderer/router/index.js

Update vue-loader version and support the new version of postcss-nesting.

Update vue-loader version

---

template/src/renderer/components/LandingPage/SystemInformation.vue

It would be helpful to include this in the template as a way to show the power of vue.

Use router values

---

README.md

I added some of my projects that uses electron-vue template.
Uber Run - https://github.com/mrgodhani/uberrun
Bookmark - https://github.com/mrgodhani/bookmark

Updated Made with electron-vue Read me

---

README.md

Hi everyone ! 
I'm happy to share with you my first open-source application : [Code Notes](https://lauthieb.github.io/code-notes) 🚀
The purpose of the application is to improve the productivity of developers with a local (for the moment) code snippet manager to collect, insert and reuse your snippets.
There is a demo of the application right there.
[![Code Notes - V1.0.0](https://img.youtube.com/vi/WiTLEyDYex4/0.jpg)](https://www.youtube.com/watch?v=WiTLEyDYex4 "Code Notes - V1.0.0")
Feel free to contribute ❤️

Add Code Notes app

---

docs/en/vue_accessories.md

Documentation change after https://github.com/SimulatedGREG/electron-vue/issues/387.
This can save a lot of time for newer people in electron and vuejs.

Clarification with usage of axios in localhost/Dev

---

README.md

Add vue-design to [Made with electron-vue]

Add vue-design to [Made with electron-vue]

---

docs/en/renderer-process.md

Fixed typo

---

README.md

In the "Made with electron-vue" part

Corrected a wrong link in READ.ME

---

docs/cn/renderer-process.md

corrected a wrong link in the vuex part

Correct wrong link

---

docs/ko/README.md
docs/ko/building_your_app.md
docs/ko/contributing.md
docs/ko/debugging-production.md
docs/ko/testing.md
docs/ko/unittesting.md
docs/ko/using-electron-builder.md
docs/ko/using-electron-packager.md
docs/ko/using_pre-processors.md

The PR you gave me before is not worthy of reference. So I will post one after each inspection.

Korean documents

---

README.md

Add an app make with electron-vue

---

docs/cn/faqs.md
docs/cn/testing.md
docs/en/faqs.md
docs/en/testing.md
docs/ja/faqs.md
docs/ja/testing.md
docs/ko/faqs.md
docs/ko/testing.md
docs/pt_BR/faqs.md
docs/pt_BR/testing.md

I fixed relative links on `.md` files that were not working.

fixed relative links on documents

---

docs/en/vue_accessories.md
meta.js
template/src/renderer/store/index.js

Use this Vuex plugin to sync Vuex store:
– https://github.com/vue-electron/vuex-electron

Sync Vuex store between all processes

---

template/src/index.ejs

fix web build

---

README.md

Hi, I add my project "Leeze" to the list.
Leeze is a receipt record app, which has a nice user interface and user experience. 
Thanks for your electron-vue structure.

Add Lezze to List

---

template/.travis.yml

fixes this issue:
https://github.com/SimulatedGREG/electron-vue/issues/753

fix(travis.yml): CI uses now node version 10

---

template/.electron-vue/webpack.main.config.js
template/.electron-vue/webpack.renderer.config.js
template/.electron-vue/webpack.web.config.js
template/package.json

to fix issues: https://github.com/SimulatedGREG/electron-vue/issues/903

fix: use babel-minify-webpack-plugin

---

docs/ko/vue_accessories.md

Correcting incorrect Korean spelling

---

docs/pt_BR/migration-guide.md
docs/pt_BR/webpack-configurations.md

- Fix some "difficult-to-understand" texts in the Migration Guide
- Add new translations to Webpack Configurations

Add new translations in Portuguese

---

docs/en/savingreading-local-files.md

Into this documentation change, I added the option to create separated datastores using NeDB.

updated docs for setting multiple localfiles in nedb

---

template/.electron-vue/webpack.renderer.config.js
template/.electron-vue/webpack.web.config.js

fixed bug : process is not defined

fix : process is not defined

---

template/.electron-vue/dev-runner.js

From https://github.com/SimulatedGREG/electron-vue/issues/437

Fix hot reload resetting whole renderer state
